version: '3'

services:
    app:
        build:
            context: .
        volumes:
            - .:/var/www/laravel
            # - ./supervisord.conf:/etc/supervisord.conf
            - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
            - ./docker/logs:/var/log
        depends_on:
            - db
            - redis
    db:
        image: postgres:alpine
        ports:
            - "5444:5432"
        environment:
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_DB: ${DB_DATABASE}
            TZ: 'GMT+2'
            PGTZ: 'GMT+2'
        volumes:
            - db-volume:/var/lib/postgresql/data
        shm_size: '2gb'

    redis:
        image: redis:alpine
        ports:
            - "6399:6379"
    nginx:
        image: nginx:alpine
        ports:
            - "8090:80"
        volumes:
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./docker/nginx/logs:/var/log/nginx
            - .:/var/www/laravel
        links:
            - app

volumes:
    db-volume:
