version: '3'

services:
    app:
        build:
            context: .
        volumes:
            - .:/var/www/laravel
            - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
        depends_on:
            - db
    db:
        image: mariadb:10.4
        ports:
            - "3306"
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: yes
        volumes:
            - ${PATH_DB_LOCAL}:/var/lib/mysql
    nginx:
        image: nginx:alpine
        ports:
            - "8090:80"
        volumes:
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./docker/nginx/logs:/var/log/nginx
            - .:/var/www/laravel
        links:
            - app

volumes:
    db-volume:
