version: '3'

services:
    app:
        build:
            context: .
        volumes:
            - .:/var/www/laravel
            - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
            - ./docker/logs:/var/log
    nginx:
        image: nginx:alpine
        ports:
            - "8090:80"
        volumes:
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./docker/nginx/logs:/var/log/nginx
            - .:/var/www/laravel
        links:
            - app
